version: '3.7'
services:
  discoveryleft:
    build:
      context:
        ./discovery-service
      dockerfile: ../docker/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        SOURCEAPP: ./target/discovery-service-0.0.1-SNAPSHOT.jar
    ports:
      - 8761:8761
    environment:
      EUREKA_LEFT_URL: http://discoveryleft:8761/eureka
      EUREKA_RIGHT_URL: http://discoveryright:8761/eureka
      TZ: Europe/Prague

  gatewayleft:
    init: true
    build:
      context:
        ./gateway-service
      dockerfile: ../docker/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        SOURCEAPP: ./target/gateway-service-0.0.1-SNAPSHOT.jar
    depends_on:
      - discoveryleft
    ports:
      - 8080:8080
    environment:
      EUREKA_LEFT_URL: http://discoveryleft:8761/eureka
      EUREKA_RIGHT_URL: http://discoveryright:8761/eureka
      EUREKA_DEFAULT_ZONE: left
      TZ: Europe/Prague


  backendleft:
    build:
      context:
        ./backend-service
      dockerfile: ../docker/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        SOURCEAPP: ./target/backend-service-0.0.1-SNAPSHOT.jar
    depends_on:
      - discoveryleft
    ports:
      - 8081:8080
    environment:
      EUREKA_LEFT_URL: http://discoveryleft:8761/eureka
      EUREKA_RIGHT_URL: http://discoveryright:8761/eureka
      EUREKA_DEFAULT_ZONE: left
      TZ: Europe/Prague

  ### RIGHT ZONE

  discoveryright:
    build:
      context:
        ./discovery-service
      dockerfile: ../docker/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        SOURCEAPP: ./target/discovery-service-0.0.1-SNAPSHOT.jar
    ports:
      - 8762:8761
    environment:
      EUREKA_LEFT_URL: http://discoveryleft:8761/eureka
      EUREKA_RIGHT_URL: http://discoveryright:8761/eureka
      TZ: Europe/Prague


  backendright:
    build:
      context:
        ./backend-service
      dockerfile: ../docker/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        SOURCEAPP: ./target/backend-service-0.0.1-SNAPSHOT.jar
    depends_on:
      - discoveryright
    ports:
      - 8082:8080
    environment:
      EUREKA_LEFT_URL: http://discoveryleft:8761/eureka
      EUREKA_RIGHT_URL: http://discoveryright:8761/eureka
      EUREKA_DEFAULT_ZONE: right
      TZ: Europe/Prague